namespace NoJsonSchema.Core.Emit;

/// <summary>
/// Static block of zero-dependency UTF-8 helpers embedded into every generated
/// <c>{Ns}Serializer.g.cs</c>. Lives in source form so it can be copied verbatim,
/// and so the user gets exactly one copy regardless of how many types are generated.
/// </summary>
/// <remarks>
/// Internally uses <c>ref byte</c> fields + <c>Unsafe.Add</c> to elide span-bounds checks on the
/// hot read/write paths. Generated code must target net7.0 (C# 11) or later — ref fields and
/// <c>Unsafe</c>/<c>MemoryMarshal</c> APIs are required.
/// </remarks>
static class SerializerTemplate
{
    public const string OptionsTypeName = "NoJsonSerializerOptions";
    public const string TokenizerTypeName = "Utf8JsonTokenizer";
    public const string WriterTypeName = "Utf8JsonBufferWriter";
    public const string FormatExceptionName = "NoJsonFormatException";

    /// <summary>
    /// Shim file emitted alongside the main serializer to provide <c>SetsRequiredMembersAttribute</c>
    /// on pre-net7 targets. The file is suppressed via <c>#if</c> on net7+ so the BCL type wins.
    /// </summary>
    public const string SetsRequiredMembersShim = """
// <auto-generated/>
#if !NET7_0_OR_GREATER
// ReSharper disable once CheckNamespace
namespace System.Diagnostics.CodeAnalysis;

[global::System.AttributeUsage(global::System.AttributeTargets.Constructor, AllowMultiple = false, Inherited = false)]
internal sealed class SetsRequiredMembersAttribute : global::System.Attribute { }
#endif
""";

    public const string SharedDefinitions = """
public sealed class NoJsonSerializerOptions
{
    public static NoJsonSerializerOptions Default { get; } = new();

    public bool StrictExtraProperties { get; init; }
    public bool WriteIndented { get; init; }
    public bool SkipNullProperties { get; init; } = true;
}

/// <summary>
/// Per-type formatter contract — the generic <c>{Ns}Serializer&lt;T&gt;</c> dispatch goes through a
/// <c>Cache&lt;T&gt;</c> static-initialised once per CLR generic instantiation, then calls into one
/// of these adapters. Keeps the hot path branch-free without sacrificing extensibility.
/// </summary>
public interface INoJsonFormatter<T>
{
    T Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options);
    void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in T value, NoJsonSerializerOptions options);

    T Deserialize(global::System.IO.Stream stream, NoJsonSerializerOptions options);
    void Serialize(global::System.IO.Stream stream, in T value, NoJsonSerializerOptions options);

    global::System.Threading.Tasks.ValueTask<T> DeserializeAsync(global::System.IO.Stream stream, NoJsonSerializerOptions options, global::System.Threading.CancellationToken cancellationToken);
    global::System.Threading.Tasks.ValueTask SerializeAsync(global::System.IO.Stream stream, T value, NoJsonSerializerOptions options, global::System.Threading.CancellationToken cancellationToken);
}

/// <summary>
/// Shared Stream &lt;-&gt; byte[] helpers. The fast path for in-memory <see cref="global::System.IO.MemoryStream"/>
/// avoids an extra copy; otherwise the full payload is collected once before parsing.
/// </summary>
internal static class NoJsonStreamUtility
{
    public static byte[] ReadAllBytes(global::System.IO.Stream stream)
    {
        if (stream is global::System.IO.MemoryStream ms && ms.TryGetBuffer(out var seg))
        {
            var copy = new byte[seg.Count];
            global::System.Buffer.BlockCopy(seg.Array!, seg.Offset, copy, 0, seg.Count);
            return copy;
        }
        using var dest = new global::System.IO.MemoryStream();
        stream.CopyTo(dest);
        return dest.ToArray();
    }

    public static async global::System.Threading.Tasks.ValueTask<byte[]> ReadAllBytesAsync(
        global::System.IO.Stream stream, global::System.Threading.CancellationToken cancellationToken)
    {
        using var dest = new global::System.IO.MemoryStream();
        await stream.CopyToAsync(dest, 81920, cancellationToken).ConfigureAwait(false);
        return dest.ToArray();
    }
}

public sealed class NoJsonFormatException : global::System.Exception
{
    public NoJsonFormatException(string message, int position, int line = 0, int column = 0)
        : base(FormatMessage(message, position, line, column))
    {
        Position = position;
        Line = line;
        Column = column;
    }

    /// <summary>Byte offset within the input where the failure was detected.</summary>
    public int Position { get; }

    /// <summary>1-based line number; 0 when not computed (e.g. constructed directly without source span).</summary>
    public int Line { get; }

    /// <summary>1-based column number on <see cref="Line"/>; 0 when not computed.</summary>
    public int Column { get; }

    static string FormatMessage(string message, int position, int line, int column) =>
        line > 0
            ? message + " (line " + line + ", column " + column + ", pos " + position + ")"
            : message + " (pos " + position + ")";
}

/// <summary>
/// Pull-style UTF-8 JSON tokenizer with a Read*/TryRead* only API surface:
/// the caller (generated formatters) always knows the expected next token from the schema.
/// </summary>
ref struct Utf8JsonTokenizer
{
    readonly ref byte head;
    readonly int length;
    int pos;
    int valueStart;
    int valueEnd;
    bool valueHasEscape;

    public Utf8JsonTokenizer(global::System.ReadOnlySpan<byte> input)
    {
        head = ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(input);
        length = input.Length;
        pos = 0;
        valueStart = 0;
        valueEnd = 0;
        valueHasEscape = false;
    }

    public int Position
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => pos;
    }

    // ----- Structural -----------------------------------------------------------------------

    public void ReadStartObject()
    {
        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)'{')
            ThrowFormatException("Expected '{'");
        pos++;
    }

    public void ReadStartArray()
    {
        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)'[')
            ThrowFormatException("Expected '['");
        pos++;
    }

    /// <summary>
    /// Inside an object: read the next property name into <paramref name="nameUtf8"/> and the
    /// trailing colon, or return false (and consume the closing '}') when the object ends.
    /// </summary>
    public bool TryReadPropertyName(out global::System.ReadOnlySpan<byte> nameUtf8)
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Unexpected end inside object");

        byte b = ByteAt(pos);
        if (b == (byte)',')
        {
            pos++;
            SkipWhitespace();
            if (pos >= length) ThrowFormatException("Unexpected end after ','");
            b = ByteAt(pos);
        }

        if (b == (byte)'}')
        {
            pos++;
            nameUtf8 = default;
            return false;
        }

        if (b != (byte)'"')
            ThrowFormatException("Expected '\"' for property name, got 0x" + b.ToString("X2"));

        ReadStringValue();
        nameUtf8 = SliceFrom(valueStart, valueEnd - valueStart);

        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)':')
            ThrowFormatException("Expected ':' after property name");
        pos++;
        return true;
    }

    /// <summary>
    /// Inside an array: consume the optional ',' separator. Returns true and consumes the
    /// closing ']' if the array ended; false when another element follows.
    /// </summary>
    public bool TryReadEndArray()
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Unexpected end inside array");

        byte b = ByteAt(pos);
        if (b == (byte)',')
        {
            pos++;
            SkipWhitespace();
            if (pos >= length) ThrowFormatException("Unexpected end after ','");
            b = ByteAt(pos);
        }

        if (b == (byte)']') { pos++; return true; }
        return false;
    }

    // ----- Optional/null --------------------------------------------------------------------

    /// <summary>If the next token is JSON <c>null</c>, advance past it and return true.</summary>
    public bool TryReadNull()
    {
        SkipWhitespace();
        if (pos + 4 <= length && ByteAt(pos) == (byte)'n'
            && SliceFrom(pos, 4).SequenceEqual("null"u8))
        {
            pos += 4;
            return true;
        }
        return false;
    }

    // ----- Value readers --------------------------------------------------------------------

    public string ReadString()
    {
        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)'"')
            ThrowFormatException("Expected string");
        ReadStringValue();
        var span = SliceFrom(valueStart, valueEnd - valueStart);
        return valueHasEscape ? DecodeString(span) : global::System.Text.Encoding.UTF8.GetString(span);
    }

    /// <summary>
    /// Read a JSON string and return its raw UTF-8 byte slice without allocating a <c>string</c>.
    /// Returns false if the string contains backslash escapes — callers should then fall back to <see cref="ReadString"/>.
    /// </summary>
    public bool TryReadStringRaw(out global::System.ReadOnlySpan<byte> rawBytes)
    {
        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)'"')
            ThrowFormatException("Expected string");
        ReadStringValue();
        if (valueHasEscape) { rawBytes = default; return false; }
        rawBytes = SliceFrom(valueStart, valueEnd - valueStart);
        return true;
    }

    public bool ReadBoolean()
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Expected boolean");
        byte b = ByteAt(pos);
        if (b == (byte)'t')
        {
            if (pos + 4 > length || !SliceFrom(pos, 4).SequenceEqual("true"u8))
                ThrowFormatException("Expected 'true'");
            pos += 4;
            return true;
        }
        if (b == (byte)'f')
        {
            if (pos + 5 > length || !SliceFrom(pos, 5).SequenceEqual("false"u8))
                ThrowFormatException("Expected 'false'");
            pos += 5;
            return false;
        }
        ThrowFormatException("Expected boolean, got 0x" + b.ToString("X2"));
        return false; // unreachable — the C# flow analyser doesn't honour [DoesNotReturn] for CS0161.
    }

    public sbyte ReadSByte()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out sbyte v, out _))
            ThrowFormatException("Invalid int8");
        return v;
    }

    public byte ReadByte()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out byte v, out _))
            ThrowFormatException("Invalid uint8");
        return v;
    }

    public short ReadInt16()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out short v, out _))
            ThrowFormatException("Invalid int16");
        return v;
    }

    public ushort ReadUInt16()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out ushort v, out _))
            ThrowFormatException("Invalid uint16");
        return v;
    }

    public int ReadInt32()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out int v, out _))
            ThrowFormatException("Invalid int32");
        return v;
    }

    public uint ReadUInt32()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out uint v, out _))
            ThrowFormatException("Invalid uint32");
        return v;
    }

    public long ReadInt64()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out long v, out _))
            ThrowFormatException("Invalid int64");
        return v;
    }

    public ulong ReadUInt64()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out ulong v, out _))
            ThrowFormatException("Invalid uint64");
        return v;
    }

    public float ReadSingle()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out float v, out _))
            ThrowFormatException("Invalid float");
        return v;
    }

    public double ReadDouble()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out double v, out _))
            ThrowFormatException("Invalid double");
        return v;
    }

    public global::System.DateTimeOffset ReadDateTimeOffset()
    {
        var s = ReadString();
        if (!global::System.DateTimeOffset.TryParse(s, global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.RoundtripKind, out var v))
            ThrowFormatException("Invalid date-time '" + s + "'");
        return v;
    }

    public global::System.Guid ReadGuid()
    {
        var s = ReadString();
        if (!global::System.Guid.TryParse(s, out var v))
            ThrowFormatException("Invalid uuid '" + s + "'");
        return v;
    }

    public global::System.DateOnly ReadDateOnly()
    {
        var s = ReadString();
        if (!global::System.DateOnly.TryParse(s, global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.None, out var v))
            ThrowFormatException("Invalid date '" + s + "'");
        return v;
    }

    public global::System.TimeOnly ReadTimeOnly()
    {
        var s = ReadString();
        if (!global::System.TimeOnly.TryParse(s, global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.None, out var v))
            ThrowFormatException("Invalid time '" + s + "'");
        return v;
    }

    public global::System.TimeSpan ReadTimeSpan()
    {
        var s = ReadString();
        // ISO 8601 duration ("PT1H30M") via XmlConvert — JSON Schema's `format: duration` mandates ISO 8601.
        try { return global::System.Xml.XmlConvert.ToTimeSpan(s); }
        catch (global::System.FormatException) { ThrowFormatException("Invalid duration '" + s + "'"); return default; }
    }

    public global::System.Uri ReadUri()
    {
        var s = ReadString();
        if (!global::System.Uri.TryCreate(s, global::System.UriKind.RelativeOrAbsolute, out var v))
            ThrowFormatException("Invalid uri '" + s + "'");
        return v;
    }

    public byte[] ReadByteArray()
    {
        var s = ReadString();
        try { return global::System.Convert.FromBase64String(s); }
        catch (global::System.FormatException) { ThrowFormatException("Invalid base64"); return []; }
    }

    // ----- Discriminator peek (polymorphic dispatch) ---------------------------------------

    /// <summary>
    /// Scan forward (without advancing the tokenizer state) for a top-level property named
    /// <paramref name="discriminatorName"/> on the current object, and return its raw UTF-8 string
    /// value via <paramref name="rawValue"/>. The caller must still be positioned just after the
    /// <c>{</c> of the object (i.e. inside it). The scan does not validate the rest of the object;
    /// it just hunts the discriminator so a polymorphic parser can dispatch to the right subtype.
    /// </summary>
    public bool TryPeekDiscriminator(
        global::System.ReadOnlySpan<byte> discriminatorName,
        out global::System.ReadOnlySpan<byte> rawValue)
    {
        rawValue = default;
        var savedPos = pos;
        var savedValueStart = valueStart;
        var savedValueEnd = valueEnd;
        var savedValueHasEscape = valueHasEscape;
        try
        {
            int depth = 0;
            while (pos < length)
            {
                SkipWhitespace();
                if (pos >= length) return false;
                byte b = ByteAt(pos);

                if (b == (byte)'{') { depth++; pos++; continue; }
                if (b == (byte)'}')
                {
                    if (depth == 0) return false; // current object ended
                    depth--; pos++; continue;
                }
                if (b == (byte)'[') { SkipObjectOrArray((byte)'[', (byte)']'); continue; }
                if (b == (byte)',' || b == (byte)':') { pos++; continue; }

                if (b != (byte)'"')
                {
                    // Skip scalar values quickly until we land on a property name or container.
                    while (pos < length)
                    {
                        var bb = ByteAt(pos);
                        if (bb == (byte)',' || bb == (byte)'}' || bb == (byte)']' || bb == (byte)' '
                            || bb == (byte)'\n' || bb == (byte)'\t' || bb == (byte)'\r') break;
                        pos++;
                    }
                    continue;
                }

                // We're on a string. Inside the *current* object (depth == 0) it's a property name;
                // anywhere deeper it's a string value to skip past.
                ReadStringValue();
                if (depth != 0) continue;

                var nameSpan = SliceFrom(valueStart, valueEnd - valueStart);

                // After the name, expect ':'.
                SkipWhitespace();
                if (pos >= length || ByteAt(pos) != (byte)':') return false;
                pos++;

                if (nameSpan.SequenceEqual(discriminatorName) && !valueHasEscape)
                {
                    SkipWhitespace();
                    if (pos >= length || ByteAt(pos) != (byte)'"') return false;
                    ReadStringValue();
                    if (valueHasEscape) return false; // peek does not unescape
                    rawValue = SliceFrom(valueStart, valueEnd - valueStart);
                    return true;
                }

                // Not the discriminator — skip the value and continue scanning.
                SkipWhitespace();
                if (pos >= length) return false;
                byte valStart = ByteAt(pos);
                if (valStart == (byte)'{') SkipObjectOrArray((byte)'{', (byte)'}');
                else if (valStart == (byte)'[') SkipObjectOrArray((byte)'[', (byte)']');
                else if (valStart == (byte)'"') ReadStringValue();
                else
                {
                    while (pos < length)
                    {
                        var bb = ByteAt(pos);
                        if (bb == (byte)',' || bb == (byte)'}' || bb == (byte)' '
                            || bb == (byte)'\n' || bb == (byte)'\t' || bb == (byte)'\r') break;
                        pos++;
                    }
                }
            }
            return false;
        }
        finally
        {
            pos = savedPos;
            valueStart = savedValueStart;
            valueEnd = savedValueEnd;
            valueHasEscape = savedValueHasEscape;
        }
    }

    // ----- Skip an unknown value -----------------------------------------------------------

    public void SkipValue()
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Unexpected end of input");
        byte b = ByteAt(pos);
        switch (b)
        {
            case (byte)'"': ReadStringValue(); return;
            case (byte)'{': SkipObjectOrArray((byte)'{', (byte)'}'); return;
            case (byte)'[': SkipObjectOrArray((byte)'[', (byte)']'); return;
            case (byte)'t': ConsumeKeyword("true"u8); return;
            case (byte)'f': ConsumeKeyword("false"u8); return;
            case (byte)'n': ConsumeKeyword("null"u8); return;
            default:
                if (b == (byte)'-' || (b >= (byte)'0' && b <= (byte)'9')) { ReadNumberValue(); return; }
                ThrowFormatException("Unexpected byte 0x" + b.ToString("X2"));
                return; // unreachable
        }
    }

    // ----- Internal helpers ----------------------------------------------------------------

    /// <summary>
    /// Throw a <see cref="NoJsonFormatException"/> annotated with the current position plus the
    /// 1-based line / column computed from the input span. Kept as a NoInlining void helper so the
    /// callers stay JIT-inlineable — `throw new ...` expressions inline far worse than a single
    /// method-call to a cold throw routine.
    /// </summary>
    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    public void ThrowFormatException(string message)
    {
        var (line, column) = ComputeLineColumn(pos);
        throw new NoJsonFormatException(message, pos, line, column);
    }

    (int Line, int Column) ComputeLineColumn(int position)
    {
        int line = 1, col = 1;
        var max = position < length ? position : length;
        for (int i = 0; i < max; i++)
        {
            if (ByteAt(i) == (byte)'\n') { line++; col = 1; }
            else col++;
        }
        return (line, col);
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    byte ByteAt(int offset) => global::System.Runtime.CompilerServices.Unsafe.Add(ref head, offset);

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    global::System.ReadOnlySpan<byte> SliceFrom(int offset, int len) =>
        global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(
            ref global::System.Runtime.CompilerServices.Unsafe.Add(ref head, offset),
            len);

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void SkipWhitespace()
    {
        while (pos < length)
        {
            byte b = ByteAt(pos);
            if (b == (byte)' ' || b == (byte)'\t' || b == (byte)'\n' || b == (byte)'\r') pos++;
            else break;
        }
    }

    /// <summary>Consume <c>"..."</c> at <c>pos</c> (opening quote required), recording valueStart/valueEnd.</summary>
    void ReadStringValue()
    {
        pos++; // skip opening quote
        valueStart = pos;
        valueHasEscape = false;
        while (pos < length)
        {
            byte b = ByteAt(pos);
            if (b == (byte)'"')
            {
                valueEnd = pos;
                pos++;
                return;
            }
            if (b == (byte)'\\')
            {
                valueHasEscape = true;
                if (pos + 1 >= length) ThrowFormatException("Truncated escape");
                byte next = ByteAt(pos + 1);
                pos += (next == (byte)'u') ? 6 : 2;
                continue;
            }
            pos++;
        }
        ThrowFormatException("Unterminated string");
    }

    void ReadNumberValue()
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Expected number");
        byte first = ByteAt(pos);
        if (first != (byte)'-' && !(first >= (byte)'0' && first <= (byte)'9'))
            ThrowFormatException("Expected number, got 0x" + first.ToString("X2"));

        valueStart = pos;
        if (first == (byte)'-') pos++;
        while (pos < length && IsNumberByte(ByteAt(pos))) pos++;
        valueEnd = pos;
    }

    void ConsumeKeyword(global::System.ReadOnlySpan<byte> keyword)
    {
        if (pos + keyword.Length > length || !SliceFrom(pos, keyword.Length).SequenceEqual(keyword))
            ThrowFormatException("Expected '" + global::System.Text.Encoding.ASCII.GetString(keyword) + "'");
        pos += keyword.Length;
    }

    void SkipObjectOrArray(byte open, byte close)
    {
        int depth = 1;
        pos++; // consume the opening byte
        while (pos < length && depth > 0)
        {
            byte b = ByteAt(pos);
            if (b == (byte)'"') { ReadStringValue(); continue; }
            if (b == open) { depth++; pos++; continue; }
            if (b == close) { depth--; pos++; continue; }
            pos++;
        }
        if (depth != 0) ThrowFormatException("Unterminated container");
    }

    static bool IsNumberByte(byte b) =>
        (b >= (byte)'0' && b <= (byte)'9') || b == (byte)'.' || b == (byte)'-' || b == (byte)'+' || b == (byte)'e' || b == (byte)'E';

    static string DecodeString(global::System.ReadOnlySpan<byte> bytes)
    {
        var sb = new global::System.Text.StringBuilder(bytes.Length);
        int i = 0;
        while (i < bytes.Length)
        {
            byte b = bytes[i];
            if (b != (byte)'\\') { sb.Append((char)b); i++; continue; }

            if (i + 1 >= bytes.Length) throw new NoJsonFormatException("Truncated escape", i);
            byte e = bytes[i + 1];
            switch (e)
            {
                case (byte)'"':  sb.Append('"');  i += 2; break;
                case (byte)'\\': sb.Append('\\'); i += 2; break;
                case (byte)'/':  sb.Append('/');  i += 2; break;
                case (byte)'b':  sb.Append('\b'); i += 2; break;
                case (byte)'f':  sb.Append('\f'); i += 2; break;
                case (byte)'n':  sb.Append('\n'); i += 2; break;
                case (byte)'r':  sb.Append('\r'); i += 2; break;
                case (byte)'t':  sb.Append('\t'); i += 2; break;
                case (byte)'u':
                {
                    if (i + 6 > bytes.Length) throw new NoJsonFormatException("Truncated \\u escape", i);
                    int cp = HexNibble(bytes[i + 2]) << 12
                           | HexNibble(bytes[i + 3]) << 8
                           | HexNibble(bytes[i + 4]) << 4
                           | HexNibble(bytes[i + 5]);
                    sb.Append((char)cp);
                    i += 6;
                    break;
                }
                default: throw new NoJsonFormatException("Unknown escape", i);
            }
        }
        return sb.ToString();
    }

    static int HexNibble(byte b)
    {
        if (b >= (byte)'0' && b <= (byte)'9') return b - (byte)'0';
        if (b >= (byte)'a' && b <= (byte)'f') return 10 + (b - (byte)'a');
        if (b >= (byte)'A' && b <= (byte)'F') return 10 + (b - (byte)'A');
        throw new NoJsonFormatException("Bad hex digit", 0);
    }
}

ref struct Utf8JsonBufferWriter
{
    readonly global::System.Buffers.IBufferWriter<byte> writer;
    ref byte spanHead;
    int spanRemaining;
    int pending;
    bool needsSeparator;

    public Utf8JsonBufferWriter(global::System.Buffers.IBufferWriter<byte> writer)
    {
        this.writer = writer;
        spanHead = ref global::System.Runtime.CompilerServices.Unsafe.NullRef<byte>();
        spanRemaining = 0;
        pending = 0;
        needsSeparator = false;
    }

    public void Flush()
    {
        if (pending > 0)
        {
            writer.Advance(pending);
            spanHead = ref global::System.Runtime.CompilerServices.Unsafe.NullRef<byte>();
            spanRemaining = 0;
            pending = 0;
        }
    }

    public void WriteStartObject() { MaybeSeparator(); AppendByte((byte)'{'); needsSeparator = false; }
    public void WriteEndObject()   { needsSeparator = false; AppendByte((byte)'}'); needsSeparator = true; }
    public void WriteStartArray()  { MaybeSeparator(); AppendByte((byte)'['); needsSeparator = false; }
    public void WriteEndArray()    { needsSeparator = false; AppendByte((byte)']'); needsSeparator = true; }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void WritePropertyNameRaw(global::System.ReadOnlySpan<byte> nameWithQuotesAndColon)
    {
        MaybeSeparator();
        Append(nameWithQuotesAndColon);
        needsSeparator = false;
    }

    /// <summary>
    /// Writes <paramref name="contentInsideQuotes"/> as a JSON string value. The bytes must be valid UTF-8
    /// and contain no characters that would require escaping (used for enum members and other fixed literals).
    /// </summary>
    public void WriteRawStringValue(scoped global::System.ReadOnlySpan<byte> contentInsideQuotes)
    {
        MaybeSeparator();
        AppendByte((byte)'"');
        Append(contentInsideQuotes);
        AppendByte((byte)'"');
        needsSeparator = true;
    }

    public void WriteNull()  { MaybeSeparator(); Append("null"u8);  needsSeparator = true; }
    public void WriteTrue()  { MaybeSeparator(); Append("true"u8);  needsSeparator = true; }
    public void WriteFalse() { MaybeSeparator(); Append("false"u8); needsSeparator = true; }
    public void WriteBoolean(bool v) { if (v) WriteTrue(); else WriteFalse(); }

    public void WriteDateTimeOffset(global::System.DateTimeOffset v)
    {
        WriteString(v.ToString("O", global::System.Globalization.CultureInfo.InvariantCulture));
    }

    public void WriteGuid(global::System.Guid v)
    {
        WriteString(v.ToString("D", global::System.Globalization.CultureInfo.InvariantCulture));
    }

    public void WriteDateOnly(global::System.DateOnly v)
    {
        WriteString(v.ToString("yyyy-MM-dd", global::System.Globalization.CultureInfo.InvariantCulture));
    }

    public void WriteTimeOnly(global::System.TimeOnly v)
    {
        WriteString(v.ToString("O", global::System.Globalization.CultureInfo.InvariantCulture));
    }

    public void WriteTimeSpan(global::System.TimeSpan v)
    {
        // Emit ISO 8601 duration (`P…T…`) so it round-trips through `format: duration` consumers.
        WriteString(global::System.Xml.XmlConvert.ToString(v));
    }

    public void WriteUri(global::System.Uri v)
    {
        WriteString(v.ToString());
    }

    public void WriteByteArray(byte[] v)
    {
        WriteString(global::System.Convert.ToBase64String(v));
    }

    public void WriteSByte(sbyte v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[8];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("sbyte format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteByte(byte v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[8];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("byte format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteInt16(short v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[8];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("short format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteUInt16(ushort v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[8];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("ushort format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteInt32(int v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[16];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("int format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteUInt32(uint v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[16];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("uint format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteInt64(long v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[24];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("long format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteUInt64(ulong v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[24];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("ulong format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteSingle(float v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[32];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("single format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteDouble(double v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[32];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("double format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteString(string value)
    {
        MaybeSeparator();
        AppendByte((byte)'"');

        var chars = value.AsSpan();
        int safeStart = 0;
        for (int i = 0; i < chars.Length; i++)
        {
            char c = chars[i];
            if (c >= 0x20 && c < 0x80 && c != '"' && c != '\\') continue;

            if (i > safeStart) AppendAsciiRange(chars.Slice(safeStart, i - safeStart));

            switch (c)
            {
                case '"':  Append2((byte)'\\', (byte)'"');  break;
                case '\\': Append2((byte)'\\', (byte)'\\'); break;
                case '\b': Append2((byte)'\\', (byte)'b');  break;
                case '\f': Append2((byte)'\\', (byte)'f');  break;
                case '\n': Append2((byte)'\\', (byte)'n');  break;
                case '\r': Append2((byte)'\\', (byte)'r');  break;
                case '\t': Append2((byte)'\\', (byte)'t');  break;
                default:
                    if (c < 0x20)
                    {
                        Ensure(6);
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 0) = (byte)'\\';
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 1) = (byte)'u';
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 2) = (byte)'0';
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 3) = (byte)'0';
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 4) = HexByte((c >> 4) & 0xF);
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 5) = HexByte(c & 0xF);
                        Advance(6);
                    }
                    else
                    {
                        int cp;
                        if (char.IsHighSurrogate(c) && i + 1 < chars.Length && char.IsLowSurrogate(chars[i + 1]))
                        {
                            cp = char.ConvertToUtf32(c, chars[i + 1]);
                            i++;
                        }
                        else cp = c;
                        WriteCodePointUtf8(cp);
                    }
                    break;
            }
            safeStart = i + 1;
        }

        if (chars.Length > safeStart) AppendAsciiRange(chars.Slice(safeStart));

        AppendByte((byte)'"');
        needsSeparator = true;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    static byte HexByte(int nibble) => nibble < 10 ? (byte)('0' + nibble) : (byte)('a' + nibble - 10);

    void AppendAsciiRange(scoped global::System.ReadOnlySpan<char> chars)
    {
        Ensure(chars.Length);
        var destSpan = global::System.Runtime.InteropServices.MemoryMarshal.CreateSpan(ref spanHead, chars.Length);
        int written = global::System.Text.Encoding.UTF8.GetBytes(chars, destSpan);
        Advance(written);
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void Append2(byte b0, byte b1)
    {
        Ensure(2);
        global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 0) = b0;
        global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 1) = b1;
        Advance(2);
    }

    void WriteCodePointUtf8(int cp)
    {
        if (cp < 0x800)
        {
            Ensure(2);
            global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 0) = (byte)(0xC0 | (cp >> 6));
            global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 1) = (byte)(0x80 | (cp & 0x3F));
            Advance(2);
        }
        else if (cp < 0x10000)
        {
            Ensure(3);
            global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 0) = (byte)(0xE0 | (cp >> 12));
            global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 1) = (byte)(0x80 | ((cp >> 6) & 0x3F));
            global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 2) = (byte)(0x80 | (cp & 0x3F));
            Advance(3);
        }
        else
        {
            Ensure(4);
            global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 0) = (byte)(0xF0 | (cp >> 18));
            global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 1) = (byte)(0x80 | ((cp >> 12) & 0x3F));
            global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 2) = (byte)(0x80 | ((cp >> 6) & 0x3F));
            global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, 3) = (byte)(0x80 | (cp & 0x3F));
            Advance(4);
        }
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void MaybeSeparator()
    {
        if (needsSeparator) AppendByte((byte)',');
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void Append(scoped global::System.ReadOnlySpan<byte> data)
    {
        Ensure(data.Length);
        global::System.Runtime.CompilerServices.Unsafe.CopyBlockUnaligned(
            ref spanHead,
            ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(data),
            (uint)data.Length);
        Advance(data.Length);
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void AppendByte(byte b)
    {
        Ensure(1);
        spanHead = b;
        Advance(1);
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void Advance(int n)
    {
        spanHead = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref spanHead, n);
        spanRemaining -= n;
        pending += n;
    }

    void Ensure(int needed)
    {
        if (spanRemaining >= needed) return;
        Flush();
        var newSpan = writer.GetSpan(needed > 256 ? needed : 256);
        spanHead = ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(newSpan);
        spanRemaining = newSpan.Length;
    }
}
""";
}
