namespace NoJsonSchema.Core.Emit;

/// <summary>
/// Zero-dependency UTF-8 helpers embedded verbatim into every generated <c>{Ns}Serializer.g.cs</c>,
/// once per assembly. Uses <c>ref byte</c> fields + <c>Unsafe.Add</c> on net7+ to elide bounds
/// checks; falls back to <c>Span&lt;byte&gt;</c> slicing on netstandard2.1 (no ref fields there).
/// </summary>
static class SerializerTemplate
{
    public const string OptionsTypeName = "NoJsonSerializerOptions";
    public const string TokenizerTypeName = "Utf8JsonTokenizer";
    public const string WriterTypeName = "Utf8JsonBufferWriter";
    public const string FormatExceptionName = "NoJsonFormatException";

    /// <summary><c>SetsRequiredMembersAttribute</c> polyfill for pre-net7 targets (BCL type wins on net7+).</summary>
    public const string SetsRequiredMembersShim = """
// <auto-generated/>
#pragma warning disable
#if !NET7_0_OR_GREATER
// ReSharper disable once CheckNamespace
namespace System.Diagnostics.CodeAnalysis;

[global::System.AttributeUsage(global::System.AttributeTargets.Constructor, AllowMultiple = false, Inherited = false)]
internal sealed class SetsRequiredMembersAttribute : global::System.Attribute { }
#endif
""";

    /// <summary><c>IsExternalInit</c> polyfill so <c>init</c> setters compile on netstandard2.0/2.1 (BCL type wins on net5+).</summary>
    public const string IsExternalInitShim = """
// <auto-generated/>
#pragma warning disable
#if !NET5_0_OR_GREATER
// ReSharper disable once CheckNamespace
namespace System.Runtime.CompilerServices;

internal static class IsExternalInit { }
#endif
""";

    public const string SharedDefinitions = """
public sealed class NoJsonSerializerOptions
{
    public static NoJsonSerializerOptions Default { get; } = new();

    public bool StrictExtraProperties { get; init; }
    public bool WriteIndented { get; init; }
    public bool SkipNullProperties { get; init; } = true;
}

public sealed class NoJsonFormatException : global::System.Exception
{
    public NoJsonFormatException(string message, int position, int line = 0, int column = 0)
        : base(FormatMessage(message, position, line, column))
    {
        Position = position;
        Line = line;
        Column = column;
    }

    public int Position { get; }
    public int Line { get; }
    public int Column { get; }

    static string FormatMessage(string message, int position, int line, int column) =>
        line > 0
            ? message + " (line " + line + ", column " + column + ", pos " + position + ")"
            : message + " (pos " + position + ")";
}

ref struct Utf8JsonTokenizer
{
#if NET7_0_OR_GREATER
    readonly ref byte head;
#else
    readonly global::System.ReadOnlySpan<byte> input;
#endif
    readonly int length;
    int pos;
    int valueStart;
    int valueEnd;
    bool valueHasEscape;

    public Utf8JsonTokenizer(global::System.ReadOnlySpan<byte> input)
    {
#if NET7_0_OR_GREATER
        head = ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(input);
#else
        this.input = input;
#endif
        length = input.Length;
        pos = 0;
        valueStart = 0;
        valueEnd = 0;
        valueHasEscape = false;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    ref byte HeadRef() =>
#if NET7_0_OR_GREATER
        ref head;
#else
        ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(input);
#endif

    public int Position
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => pos;
    }

    public void ReadStartObject()
    {
        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)'{')
            ThrowFormatException("Expected '{'");
        pos++;
    }

    public void ReadStartArray()
    {
        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)'[')
            ThrowFormatException("Expected '['");
        pos++;
    }

    public bool TryReadPropertyName(out global::System.ReadOnlySpan<byte> nameUtf8)
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Unexpected end inside object");

        byte b = ByteAt(pos);
        if (b == (byte)',')
        {
            pos++;
            SkipWhitespace();
            if (pos >= length) ThrowFormatException("Unexpected end after ','");
            b = ByteAt(pos);
        }

        if (b == (byte)'}')
        {
            pos++;
            nameUtf8 = default;
            return false;
        }

        if (b != (byte)'"')
            ThrowFormatException("Expected '\"' for property name, got 0x" + b.ToString("X2"));

        ReadStringValue();
        nameUtf8 = SliceFrom(valueStart, valueEnd - valueStart);

        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)':')
            ThrowFormatException("Expected ':' after property name");
        pos++;
        return true;
    }

    public bool TryReadEndArray()
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Unexpected end inside array");

        byte b = ByteAt(pos);
        if (b == (byte)',')
        {
            pos++;
            SkipWhitespace();
            if (pos >= length) ThrowFormatException("Unexpected end after ','");
            b = ByteAt(pos);
        }

        if (b == (byte)']') { pos++; return true; }
        return false;
    }

    public bool TryReadNull()
    {
        SkipWhitespace();
        if (pos + 4 <= length && ByteAt(pos) == (byte)'n'
            && SliceFrom(pos, 4).SequenceEqual("null"u8))
        {
            pos += 4;
            return true;
        }
        return false;
    }

    public string ReadString()
    {
        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)'"')
            ThrowFormatException("Expected string");
        ReadStringValue();
        var span = SliceFrom(valueStart, valueEnd - valueStart);
        return valueHasEscape ? DecodeString(span) : global::System.Text.Encoding.UTF8.GetString(span);
    }

    /// <summary>Raw UTF-8 slice with no <c>string</c> allocation; returns false on escapes (caller falls back to <see cref="ReadString"/>).</summary>
    public bool TryReadStringRaw(out global::System.ReadOnlySpan<byte> rawBytes)
    {
        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)'"')
            ThrowFormatException("Expected string");
        ReadStringValue();
        if (valueHasEscape) { rawBytes = default; return false; }
        rawBytes = SliceFrom(valueStart, valueEnd - valueStart);
        return true;
    }

    public bool ReadBoolean()
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Expected boolean");
        byte b = ByteAt(pos);
        if (b == (byte)'t')
        {
            if (pos + 4 > length || !SliceFrom(pos, 4).SequenceEqual("true"u8))
                ThrowFormatException("Expected 'true'");
            pos += 4;
            return true;
        }
        if (b == (byte)'f')
        {
            if (pos + 5 > length || !SliceFrom(pos, 5).SequenceEqual("false"u8))
                ThrowFormatException("Expected 'false'");
            pos += 5;
            return false;
        }
        ThrowFormatException("Expected boolean, got 0x" + b.ToString("X2"));
        return false; // unreachable; [DoesNotReturn] on ThrowFormatException isn't honoured for CS0161.
    }

    public sbyte ReadSByte()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out sbyte v, out _))
            ThrowFormatException("Invalid int8");
        return v;
    }

    public byte ReadByte()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out byte v, out _))
            ThrowFormatException("Invalid uint8");
        return v;
    }

    public short ReadInt16()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out short v, out _))
            ThrowFormatException("Invalid int16");
        return v;
    }

    public ushort ReadUInt16()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out ushort v, out _))
            ThrowFormatException("Invalid uint16");
        return v;
    }

    public int ReadInt32()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out int v, out _))
            ThrowFormatException("Invalid int32");
        return v;
    }

    public uint ReadUInt32()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out uint v, out _))
            ThrowFormatException("Invalid uint32");
        return v;
    }

    public long ReadInt64()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out long v, out _))
            ThrowFormatException("Invalid int64");
        return v;
    }

    public ulong ReadUInt64()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out ulong v, out _))
            ThrowFormatException("Invalid uint64");
        return v;
    }

    public float ReadSingle()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out float v, out _))
            ThrowFormatException("Invalid float");
        return v;
    }

    public double ReadDouble()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out double v, out _))
            ThrowFormatException("Invalid double");
        return v;
    }

    public global::System.DateTimeOffset ReadDateTimeOffset()
    {
        var s = ReadString();
        if (!global::System.DateTimeOffset.TryParse(s, global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.RoundtripKind, out var v))
            ThrowFormatException("Invalid date-time '" + s + "'");
        return v;
    }

    public global::System.Guid ReadGuid()
    {
        var s = ReadString();
        if (!global::System.Guid.TryParse(s, out var v))
            ThrowFormatException("Invalid uuid '" + s + "'");
        return v;
    }

#if NET6_0_OR_GREATER
    public global::System.DateOnly ReadDateOnly()
    {
        var s = ReadString();
        if (!global::System.DateOnly.TryParse(s, global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.None, out var v))
            ThrowFormatException("Invalid date '" + s + "'");
        return v;
    }

    public global::System.TimeOnly ReadTimeOnly()
    {
        var s = ReadString();
        if (!global::System.TimeOnly.TryParse(s, global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.None, out var v))
            ThrowFormatException("Invalid time '" + s + "'");
        return v;
    }
#endif

    public global::System.TimeSpan ReadTimeSpan()
    {
        var s = ReadString();
        try { return global::System.Xml.XmlConvert.ToTimeSpan(s); }
        catch (global::System.FormatException) { ThrowFormatException("Invalid duration '" + s + "'"); return default; }
    }

    public global::System.Uri ReadUri()
    {
        var s = ReadString();
        if (!global::System.Uri.TryCreate(s, global::System.UriKind.RelativeOrAbsolute, out var v))
            ThrowFormatException("Invalid uri '" + s + "'");
        return v;
    }

    public byte[] ReadByteArray()
    {
        var s = ReadString();
        try { return global::System.Convert.FromBase64String(s); }
        catch (global::System.FormatException) { ThrowFormatException("Invalid base64"); return []; }
    }

    public bool TryPeekDiscriminator(
        global::System.ReadOnlySpan<byte> discriminatorName,
        out global::System.ReadOnlySpan<byte> rawValue)
    {
        rawValue = default;
        var savedPos = pos;
        var savedValueStart = valueStart;
        var savedValueEnd = valueEnd;
        var savedValueHasEscape = valueHasEscape;
        try
        {
            int depth = 0;
            while (pos < length)
            {
                SkipWhitespace();
                if (pos >= length) return false;
                byte b = ByteAt(pos);

                if (b == (byte)'{') { depth++; pos++; continue; }
                if (b == (byte)'}')
                {
                    if (depth == 0) return false;
                    depth--; pos++; continue;
                }
                if (b == (byte)'[') { SkipObjectOrArray((byte)'[', (byte)']'); continue; }
                if (b == (byte)',' || b == (byte)':') { pos++; continue; }

                if (b != (byte)'"')
                {
                    while (pos < length)
                    {
                        var bb = ByteAt(pos);
                        if (bb == (byte)',' || bb == (byte)'}' || bb == (byte)']' || bb == (byte)' '
                            || bb == (byte)'\n' || bb == (byte)'\t' || bb == (byte)'\r') break;
                        pos++;
                    }
                    continue;
                }

                // depth == 0: property name; deeper: a string value to skip past.
                ReadStringValue();
                if (depth != 0) continue;

                var nameSpan = SliceFrom(valueStart, valueEnd - valueStart);

                SkipWhitespace();
                if (pos >= length || ByteAt(pos) != (byte)':') return false;
                pos++;

                if (nameSpan.SequenceEqual(discriminatorName) && !valueHasEscape)
                {
                    SkipWhitespace();
                    if (pos >= length || ByteAt(pos) != (byte)'"') return false;
                    ReadStringValue();
                    if (valueHasEscape) return false; // peek does not unescape
                    rawValue = SliceFrom(valueStart, valueEnd - valueStart);
                    return true;
                }

                SkipWhitespace();
                if (pos >= length) return false;
                byte valStart = ByteAt(pos);
                if (valStart == (byte)'{') SkipObjectOrArray((byte)'{', (byte)'}');
                else if (valStart == (byte)'[') SkipObjectOrArray((byte)'[', (byte)']');
                else if (valStart == (byte)'"') ReadStringValue();
                else
                {
                    while (pos < length)
                    {
                        var bb = ByteAt(pos);
                        if (bb == (byte)',' || bb == (byte)'}' || bb == (byte)' '
                            || bb == (byte)'\n' || bb == (byte)'\t' || bb == (byte)'\r') break;
                        pos++;
                    }
                }
            }
            return false;
        }
        finally
        {
            pos = savedPos;
            valueStart = savedValueStart;
            valueEnd = savedValueEnd;
            valueHasEscape = savedValueHasEscape;
        }
    }

    public void SkipValue()
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Unexpected end of input");
        byte b = ByteAt(pos);
        switch (b)
        {
            case (byte)'"': ReadStringValue(); return;
            case (byte)'{': SkipObjectOrArray((byte)'{', (byte)'}'); return;
            case (byte)'[': SkipObjectOrArray((byte)'[', (byte)']'); return;
            case (byte)'t': ConsumeKeyword("true"u8); return;
            case (byte)'f': ConsumeKeyword("false"u8); return;
            case (byte)'n': ConsumeKeyword("null"u8); return;
            default:
                if (b == (byte)'-' || (b >= (byte)'0' && b <= (byte)'9')) { ReadNumberValue(); return; }
                ThrowFormatException("Unexpected byte 0x" + b.ToString("X2"));
                return;
        }
    }

    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    public void ThrowFormatException(string message)
    {
        var (line, column) = ComputeLineColumn(pos);
        throw new NoJsonFormatException(message, pos, line, column);
    }

    (int Line, int Column) ComputeLineColumn(int position)
    {
        int line = 1, col = 1;
        var max = position < length ? position : length;
        for (int i = 0; i < max; i++)
        {
            if (ByteAt(i) == (byte)'\n') { line++; col = 1; }
            else col++;
        }
        return (line, col);
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    byte ByteAt(int offset) => global::System.Runtime.CompilerServices.Unsafe.Add(ref HeadRef(), offset);

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    global::System.ReadOnlySpan<byte> SliceFrom(int offset, int len) =>
        global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(
            ref global::System.Runtime.CompilerServices.Unsafe.Add(ref HeadRef(), offset),
            len);

#if NET8_0_OR_GREATER
    // Vectorized membership scans via the BCL (AVX2/AVX-512 internally) beat a hand-rolled Vector128.
    static readonly global::System.Buffers.SearchValues<byte> s_whitespace =
        global::System.Buffers.SearchValues.Create(" \t\n\r"u8);
    static readonly global::System.Buffers.SearchValues<byte> s_stringDelimiters =
        global::System.Buffers.SearchValues.Create(StringDelimiterBytes());

    static byte[] StringDelimiterBytes()
    {
        var bytes = new byte[34]; // control chars 0x00..0x1F, plus '"' and '\\'
        for (int i = 0; i < 0x20; i++) bytes[i] = (byte)i;
        bytes[0x20] = (byte)'"';
        bytes[0x21] = (byte)'\\';
        return bytes;
    }
#endif

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void SkipWhitespace()
    {
        // Scalar fast-exit: pos usually already sits on non-whitespace (compact input, or an
        // upstream peek already skipped), so avoid the IndexOfAnyExcept call in the common case.
        if (pos >= length) return;
        byte b0 = ByteAt(pos);
        if (b0 != (byte)' ' && b0 != (byte)'\t' && b0 != (byte)'\n' && b0 != (byte)'\r') return;
#if NET8_0_OR_GREATER
        int rel = global::System.MemoryExtensions.IndexOfAnyExcept(SliceFrom(pos, length - pos), s_whitespace);
        pos = rel < 0 ? length : pos + rel;
#else
        while (pos < length)
        {
            byte b = ByteAt(pos);
            if (b == (byte)' ' || b == (byte)'\t' || b == (byte)'\n' || b == (byte)'\r') pos++;
            else break;
        }
#endif
    }

    void ReadStringValue()
    {
        pos++; // opening quote
        valueStart = pos;
        valueHasEscape = false;
        while (pos < length)
        {
#if NET8_0_OR_GREATER
            // Jump to the next closing quote / escape / control char; re-entered after each escape.
            int rel = global::System.MemoryExtensions.IndexOfAny(SliceFrom(pos, length - pos), s_stringDelimiters);
            if (rel < 0) break;
            pos += rel;
#endif
            byte b = ByteAt(pos);
            if (b == (byte)'"')
            {
                valueEnd = pos;
                pos++;
                return;
            }
            if (b == (byte)'\\')
            {
                valueHasEscape = true;
                if (pos + 1 >= length) ThrowFormatException("Truncated escape");
                byte next = ByteAt(pos + 1);
                pos += (next == (byte)'u') ? 6 : 2;
                continue;
            }
            pos++;
        }
        ThrowFormatException("Unterminated string");
    }

    void ReadNumberValue()
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Expected number");
        byte first = ByteAt(pos);
        if (first != (byte)'-' && !(first >= (byte)'0' && first <= (byte)'9'))
            ThrowFormatException("Expected number, got 0x" + first.ToString("X2"));

        valueStart = pos;
        if (first == (byte)'-') pos++;
        while (pos < length && IsNumberByte(ByteAt(pos))) pos++;
        valueEnd = pos;
    }

    void ConsumeKeyword(global::System.ReadOnlySpan<byte> keyword)
    {
        if (pos + keyword.Length > length || !SliceFrom(pos, keyword.Length).SequenceEqual(keyword))
            ThrowFormatException("Expected '" + global::System.Text.Encoding.ASCII.GetString(keyword) + "'");
        pos += keyword.Length;
    }

    void SkipObjectOrArray(byte open, byte close)
    {
        int depth = 1;
        pos++; // opening byte
        while (pos < length && depth > 0)
        {
            byte b = ByteAt(pos);
            if (b == (byte)'"') { ReadStringValue(); continue; }
            if (b == open) { depth++; pos++; continue; }
            if (b == close) { depth--; pos++; continue; }
            pos++;
        }
        if (depth != 0) ThrowFormatException("Unterminated container");
    }

    static bool IsNumberByte(byte b) =>
        (b >= (byte)'0' && b <= (byte)'9') || b == (byte)'.' || b == (byte)'-' || b == (byte)'+' || b == (byte)'e' || b == (byte)'E';

    static string DecodeString(global::System.ReadOnlySpan<byte> bytes)
    {
        var sb = new global::System.Text.StringBuilder(bytes.Length);
        int i = 0;
        while (i < bytes.Length)
        {
            byte b = bytes[i];
            if (b != (byte)'\\') { sb.Append((char)b); i++; continue; }

            if (i + 1 >= bytes.Length) throw new NoJsonFormatException("Truncated escape", i);
            byte e = bytes[i + 1];
            switch (e)
            {
                case (byte)'"':  sb.Append('"');  i += 2; break;
                case (byte)'\\': sb.Append('\\'); i += 2; break;
                case (byte)'/':  sb.Append('/');  i += 2; break;
                case (byte)'b':  sb.Append('\b'); i += 2; break;
                case (byte)'f':  sb.Append('\f'); i += 2; break;
                case (byte)'n':  sb.Append('\n'); i += 2; break;
                case (byte)'r':  sb.Append('\r'); i += 2; break;
                case (byte)'t':  sb.Append('\t'); i += 2; break;
                case (byte)'u':
                {
                    if (i + 6 > bytes.Length) throw new NoJsonFormatException("Truncated \\u escape", i);
                    int cp = HexNibble(bytes[i + 2]) << 12
                           | HexNibble(bytes[i + 3]) << 8
                           | HexNibble(bytes[i + 4]) << 4
                           | HexNibble(bytes[i + 5]);
                    sb.Append((char)cp);
                    i += 6;
                    break;
                }
                default: throw new NoJsonFormatException("Unknown escape", i);
            }
        }
        return sb.ToString();
    }

    static int HexNibble(byte b)
    {
        if (b >= (byte)'0' && b <= (byte)'9') return b - (byte)'0';
        if (b >= (byte)'a' && b <= (byte)'f') return 10 + (b - (byte)'a');
        if (b >= (byte)'A' && b <= (byte)'F') return 10 + (b - (byte)'A');
        throw new NoJsonFormatException("Bad hex digit", 0);
    }
}

ref struct Utf8JsonBufferWriter
{
    readonly global::System.Buffers.IBufferWriter<byte> writer;
#if NET7_0_OR_GREATER
    ref byte bufferReference;
#else
    global::System.Span<byte> bufferReference;
#endif
    int spanRemaining;
    int pending;
    bool needsSeparator;

    public Utf8JsonBufferWriter(global::System.Buffers.IBufferWriter<byte> writer)
    {
        this.writer = writer;
#if NET7_0_OR_GREATER
        bufferReference = ref global::System.Runtime.CompilerServices.Unsafe.NullRef<byte>();
#else
        bufferReference = default;
#endif
        spanRemaining = 0;
        pending = 0;
        needsSeparator = false;
    }

    public void Flush()
    {
        if (pending > 0)
        {
            writer.Advance(pending);
#if NET7_0_OR_GREATER
            bufferReference = ref global::System.Runtime.CompilerServices.Unsafe.NullRef<byte>();
#else
            bufferReference = default;
#endif
            spanRemaining = 0;
            pending = 0;
        }
    }

    // Writable ref byte at offset past the write head; used as an assignment LHS (`GetByte(3) = b;`).
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    ref byte GetByte(int offset) =>
#if NET7_0_OR_GREATER
        ref global::System.Runtime.CompilerServices.Unsafe.Add(ref bufferReference, offset);
#else
        ref global::System.Runtime.CompilerServices.Unsafe.Add(
            ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(bufferReference),
            offset);
#endif

    public void WriteStartObject() { MaybeSeparator(); AppendByte((byte)'{'); needsSeparator = false; }
    public void WriteEndObject()   { needsSeparator = false; AppendByte((byte)'}'); needsSeparator = true; }
    public void WriteStartArray()  { MaybeSeparator(); AppendByte((byte)'['); needsSeparator = false; }
    public void WriteEndArray()    { needsSeparator = false; AppendByte((byte)']'); needsSeparator = true; }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void WritePropertyNameRaw(global::System.ReadOnlySpan<byte> nameWithQuotesAndColon)
    {
        MaybeSeparator();
        Append(nameWithQuotesAndColon);
        needsSeparator = false;
    }

    /// <summary>Writes pre-validated UTF-8 with no escaping (enum members, fixed literals).</summary>
    public void WriteRawStringValue(scoped global::System.ReadOnlySpan<byte> contentInsideQuotes)
    {
        MaybeSeparator();
        AppendByte((byte)'"');
        Append(contentInsideQuotes);
        AppendByte((byte)'"');
        needsSeparator = true;
    }

    public void WriteNull()  { MaybeSeparator(); Append("null"u8);  needsSeparator = true; }
    public void WriteTrue()  { MaybeSeparator(); Append("true"u8);  needsSeparator = true; }
    public void WriteFalse() { MaybeSeparator(); Append("false"u8); needsSeparator = true; }
    public void WriteBoolean(bool v) { if (v) WriteTrue(); else WriteFalse(); }

    public void WriteDateTimeOffset(global::System.DateTimeOffset v)
    {
        WriteString(v.ToString("O", global::System.Globalization.CultureInfo.InvariantCulture));
    }

    public void WriteGuid(global::System.Guid v)
    {
        WriteString(v.ToString("D", global::System.Globalization.CultureInfo.InvariantCulture));
    }

#if NET6_0_OR_GREATER
    public void WriteDateOnly(global::System.DateOnly v)
    {
        WriteString(v.ToString("yyyy-MM-dd", global::System.Globalization.CultureInfo.InvariantCulture));
    }

    public void WriteTimeOnly(global::System.TimeOnly v)
    {
        WriteString(v.ToString("O", global::System.Globalization.CultureInfo.InvariantCulture));
    }
#endif

    public void WriteTimeSpan(global::System.TimeSpan v)
    {
        WriteString(global::System.Xml.XmlConvert.ToString(v));
    }

    public void WriteUri(global::System.Uri v)
    {
        WriteString(v.ToString());
    }

    public void WriteByteArray(byte[] v)
    {
        WriteString(global::System.Convert.ToBase64String(v));
    }

    public void WriteSByte(sbyte v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[8];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("sbyte format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteByte(byte v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[8];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("byte format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteInt16(short v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[8];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("short format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteUInt16(ushort v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[8];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("ushort format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteInt32(int v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[16];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("int format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteUInt32(uint v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[16];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("uint format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteInt64(long v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[24];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("long format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteUInt64(ulong v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[24];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("ulong format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteSingle(float v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[32];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("single format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteDouble(double v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[32];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("double format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteString(string value)
    {
        MaybeSeparator();
        AppendByte((byte)'"');

        var chars = value.AsSpan();
        int safeStart = 0;
        for (int i = 0; i < chars.Length; i++)
        {
            char c = chars[i];
            if (c >= 0x20 && c < 0x80 && c != '"' && c != '\\') continue;

            if (i > safeStart) AppendAsciiRange(chars.Slice(safeStart, i - safeStart));

            switch (c)
            {
                case '"':  Append2((byte)'\\', (byte)'"');  break;
                case '\\': Append2((byte)'\\', (byte)'\\'); break;
                case '\b': Append2((byte)'\\', (byte)'b');  break;
                case '\f': Append2((byte)'\\', (byte)'f');  break;
                case '\n': Append2((byte)'\\', (byte)'n');  break;
                case '\r': Append2((byte)'\\', (byte)'r');  break;
                case '\t': Append2((byte)'\\', (byte)'t');  break;
                default:
                    if (c < 0x20)
                    {
                        Ensure(6);
                        GetByte(0) = (byte)'\\';
                        GetByte(1) = (byte)'u';
                        GetByte(2) = (byte)'0';
                        GetByte(3) = (byte)'0';
                        GetByte(4) = HexByte((c >> 4) & 0xF);
                        GetByte(5) = HexByte(c & 0xF);
                        Advance(6);
                    }
                    else
                    {
                        int cp;
                        if (char.IsHighSurrogate(c) && i + 1 < chars.Length && char.IsLowSurrogate(chars[i + 1]))
                        {
                            cp = char.ConvertToUtf32(c, chars[i + 1]);
                            i++;
                        }
                        else cp = c;
                        WriteCodePointUtf8(cp);
                    }
                    break;
            }
            safeStart = i + 1;
        }

        if (chars.Length > safeStart) AppendAsciiRange(chars.Slice(safeStart));

        AppendByte((byte)'"');
        needsSeparator = true;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    static byte HexByte(int nibble) => nibble < 10 ? (byte)('0' + nibble) : (byte)('a' + nibble - 10);

    void AppendAsciiRange(scoped global::System.ReadOnlySpan<char> chars)
    {
        Ensure(chars.Length);
#if NET7_0_OR_GREATER
        var destSpan = global::System.Runtime.InteropServices.MemoryMarshal.CreateSpan(ref bufferReference, chars.Length);
#else
        var destSpan = bufferReference.Slice(0, chars.Length);
#endif
        int written = global::System.Text.Encoding.UTF8.GetBytes(chars, destSpan);
        Advance(written);
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void Append2(byte b0, byte b1)
    {
        Ensure(2);
        GetByte(0) = b0;
        GetByte(1) = b1;
        Advance(2);
    }

    void WriteCodePointUtf8(int cp)
    {
        if (cp < 0x800)
        {
            Ensure(2);
            GetByte(0) = (byte)(0xC0 | (cp >> 6));
            GetByte(1) = (byte)(0x80 | (cp & 0x3F));
            Advance(2);
        }
        else if (cp < 0x10000)
        {
            Ensure(3);
            GetByte(0) = (byte)(0xE0 | (cp >> 12));
            GetByte(1) = (byte)(0x80 | ((cp >> 6) & 0x3F));
            GetByte(2) = (byte)(0x80 | (cp & 0x3F));
            Advance(3);
        }
        else
        {
            Ensure(4);
            GetByte(0) = (byte)(0xF0 | (cp >> 18));
            GetByte(1) = (byte)(0x80 | ((cp >> 12) & 0x3F));
            GetByte(2) = (byte)(0x80 | ((cp >> 6) & 0x3F));
            GetByte(3) = (byte)(0x80 | (cp & 0x3F));
            Advance(4);
        }
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void MaybeSeparator()
    {
        if (needsSeparator) AppendByte((byte)',');
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void Append(scoped global::System.ReadOnlySpan<byte> data)
    {
        Ensure(data.Length);
        global::System.Runtime.CompilerServices.Unsafe.CopyBlockUnaligned(
            ref GetByte(0),
            ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(data),
            (uint)data.Length);
        Advance(data.Length);
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void AppendByte(byte b)
    {
        Ensure(1);
        GetByte(0) = b;
        Advance(1);
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void Advance(int n)
    {
#if NET7_0_OR_GREATER
        bufferReference = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref bufferReference, n);
#else
        bufferReference = bufferReference.Slice(n);
#endif
        spanRemaining -= n;
        pending += n;
    }

    void Ensure(int needed)
    {
        if (spanRemaining >= needed) return;
        Flush();
        var newSpan = writer.GetSpan(needed > 256 ? needed : 256);
#if NET7_0_OR_GREATER
        bufferReference = ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(newSpan);
#else
        bufferReference = newSpan;
#endif
        spanRemaining = newSpan.Length;
    }
}
""";
}
