using NoJsonSchema.Core.Ir;
using NoJsonSchema.Core.Naming;

namespace NoJsonSchema.Core.Emit;

/// <summary>
/// Emits a POCO file (<c>{Type}.g.cs</c>) for a single <see cref="ObjectTypeDescriptor"/>.
/// </summary>
public static class TypeEmitter
{
    public static string Emit(ObjectTypeDescriptor type, GenerationOptions options)
    {
        if (type.Style == TypeStyle.ReadonlyRecordStruct)
        {
            return EmitRecordStruct(type, options);
        }
        return EmitClassOrRecord(type, options);
    }

    static string EmitClassOrRecord(ObjectTypeDescriptor type, GenerationOptions options)
    {
        var w = new SourceWriter();
        WriteFileHeader(w);
        w.WriteLine($"namespace {options.Namespace};");
        w.WriteLine();

        EmitXmlDoc(w, type.Description);
        var modifier = type.IsAbstract ? "abstract " : "";
        var keyword = options.TypeStyle == TypeStyle.Record ? "partial record" : "partial class";
        var inheritance = type.BaseTypeName is null
            ? ""
            : " : " + NameFactory.EscapeIfReserved(type.BaseTypeName);
        using (w.Block($"public {modifier}{keyword} {NameFactory.EscapeIfReserved(type.Name)}{inheritance}"))
        {
            for (var i = 0; i < type.Properties.Count; i++)
            {
                if (i > 0) w.WriteLine();
                EmitProperty(w, type.Properties[i], options.TypeStyle);
            }
        }

        return w.ToString();
    }

    /// <summary>
    /// Emit a value-object style declaration: <c>public readonly partial record struct T(P1 X, P2 Y);</c>.
    /// Required + non-null parameters come first; everything else is given a default so callers can
    /// construct it with positional args even when the schema marks a field optional.
    /// </summary>
    static string EmitRecordStruct(ObjectTypeDescriptor type, GenerationOptions options)
    {
        var w = new SourceWriter();
        WriteFileHeader(w);
        w.WriteLine($"namespace {options.Namespace};");
        w.WriteLine();

        EmitXmlDoc(w, type.Description);

        var ordered = type.Properties
            .Select(p => (Prop: p, Required: p.IsRequired && !p.IsNullable))
            .OrderByDescending(x => x.Required)
            .ToList();

        foreach (var (p, _) in ordered)
        {
            if (string.IsNullOrEmpty(p.Description)) continue;
            var lines = p.Description!.Split('\n');
            foreach (var line in lines)
            {
                w.WriteLine("/// <param name=\"" + NameFactory.EscapeIfReserved(p.Name) + "\">"
                    + System.Net.WebUtility.HtmlEncode(line.TrimEnd('\r')) + "</param>");
            }
        }

        var parts = new List<string>(ordered.Count);
        foreach (var (p, isRequired) in ordered)
        {
            var typeExpr = RenderPropertyType(p);
            var paramName = NameFactory.EscapeIfReserved(p.Name);
            var paramDecl = $"{typeExpr} {paramName}";
            if (!isRequired)
            {
                paramDecl += " = " + DefaultLiteral(p);
            }
            parts.Add(paramDecl);
        }

        var paramList = string.Join(", ", parts);
        w.WriteLine($"public readonly partial record struct {NameFactory.EscapeIfReserved(type.Name)}({paramList});");
        return w.ToString();
    }

    static string DefaultLiteral(PropertyDescriptor p)
    {
        // Nullable annotation already appended in RenderPropertyType for optional/nullable values.
        if (p.IsNullable || !p.IsRequired)
        {
            return TypeExpression.IsValueType(p.Type) ? "default" : "null";
        }
        return "default";
    }

    internal static void WriteFileHeader(SourceWriter w)
    {
        w.WriteLine("// <auto-generated/>");
        w.WriteLine("#nullable enable");
        w.WriteLine();
    }

    internal static void EmitXmlDoc(SourceWriter w, string? text)
    {
        if (string.IsNullOrEmpty(text)) return;

        var lines = text!.Split('\n');
        w.WriteLine("/// <summary>");
        foreach (var line in lines)
        {
            var trimmed = line.TrimEnd('\r');
            w.WriteLine("/// " + System.Net.WebUtility.HtmlEncode(trimmed));
        }
        w.WriteLine("/// </summary>");
    }

    static void EmitProperty(SourceWriter w, PropertyDescriptor p, TypeStyle style)
    {
        EmitXmlDoc(w, p.Description);
        var typeExpr = RenderPropertyType(p);
        var name = NameFactory.EscapeIfReserved(p.Name);
        var accessors = style == TypeStyle.Record ? "{ get; init; }" : "{ get; set; }";
        var modifier = p.HidesBaseProperty ? "new " : "";
        w.WriteLine($"public {modifier}{typeExpr} {name} {accessors}");
    }

    static string RenderPropertyType(PropertyDescriptor p)
    {
        var expr = TypeExpression.Render(p.Type);
        if (p.IsRequired && !p.IsNullable) return expr;
        return expr.EndsWith("?", StringComparison.Ordinal) ? expr : expr + "?";
    }
}
