using NoJsonSchema.Core.Ir;
using NoJsonSchema.Core.Naming;

namespace NoJsonSchema.Core.Emit;

/// <summary>
/// Emits a POCO file (<c>{Type}.g.cs</c>) for a single <see cref="ObjectTypeDescriptor"/>.
/// </summary>
public static class TypeEmitter
{
    public static string Emit(ObjectTypeDescriptor type, GenerationOptions options)
    {
        var w = new SourceWriter();
        WriteFileHeader(w);
        w.WriteLine($"namespace {options.Namespace};");
        w.WriteLine();

        EmitXmlDoc(w, type.Description);
        var modifier = type.IsAbstract ? "abstract " : "";
        var keyword = options.TypeStyle == TypeStyle.Record ? "partial record" : "partial class";
        var inheritance = type.BaseTypeName is null
            ? ""
            : " : " + NameFactory.EscapeIfReserved(type.BaseTypeName);
        using (w.Block($"public {modifier}{keyword} {NameFactory.EscapeIfReserved(type.Name)}{inheritance}"))
        {
            for (var i = 0; i < type.Properties.Count; i++)
            {
                if (i > 0) w.WriteLine();
                EmitProperty(w, type.Properties[i], options.TypeStyle);
            }
        }

        return w.ToString();
    }

    internal static void WriteFileHeader(SourceWriter w)
    {
        w.WriteLine("// <auto-generated/>");
        w.WriteLine("#nullable enable");
        w.WriteLine();
    }

    internal static void EmitXmlDoc(SourceWriter w, string? text)
    {
        if (string.IsNullOrEmpty(text)) return;

        var lines = text!.Split('\n');
        w.WriteLine("/// <summary>");
        foreach (var line in lines)
        {
            var trimmed = line.TrimEnd('\r');
            w.WriteLine("/// " + System.Net.WebUtility.HtmlEncode(trimmed));
        }
        w.WriteLine("/// </summary>");
    }

    static void EmitProperty(SourceWriter w, PropertyDescriptor p, TypeStyle style)
    {
        EmitXmlDoc(w, p.Description);
        var typeExpr = RenderPropertyType(p);
        var name = NameFactory.EscapeIfReserved(p.Name);
        var accessors = style == TypeStyle.Record ? "{ get; init; }" : "{ get; set; }";
        var modifier = p.HidesBaseProperty ? "new " : "";
        w.WriteLine($"public {modifier}{typeExpr} {name} {accessors}");
    }

    static string RenderPropertyType(PropertyDescriptor p)
    {
        var expr = TypeExpression.Render(p.Type);
        if (p.IsRequired && !p.IsNullable) return expr;
        return expr.EndsWith("?", StringComparison.Ordinal) ? expr : expr + "?";
    }
}
